---
title: "Questions"
execute:
  enabled: true
  echo: true
  cache: true
format:
  html:
    code-fold: false
jupyter: python3
diagram:
  cache: true
  cache-dir: ./cache
  engine:
    tikz:
      execpath: lualatex
filters:
  - diagram
---

```{=html}
<style>
/* Initialize a counter for the table */
table {
  counter-reset: rowNumber;
}

/* Increment the counter for each row in tbody */
tbody tr {
  counter-increment: rowNumber;
}

/* Display the counter in the first cell of each row */
tbody tr td:first-child::before {
  content: counter(rowNumber) ". ";
}
</style>
```

|Питання|Матеріали|
|----|----|
|Біологія нейромереж.|[Лекція 1](dl_lec1.qmd)|
|Опис роботи перцептрона.|[Лекція 1](dl_lec1.qmd), [Лекція 2](dl_lec2.qmd) |
|Градієнтний спуск. Опис алгоритму.|[Лекція 1](dl_lec1.qmd), [Лекція 2](dl_lec2.qmd),  <https://d2l.ai/chapter_optimization/gd.html>|
|Логістична регресія, побудована з використанням нейронних мереж.|[Лекція 2](dl_lec2.qmd), [Лаб 1](dl_lab1.qmd)|
|Універсальна теорема апроксимації|[Лекція 2](dl_lec2.qmd)|
|Функції активації та їх властивості. Теорема про тотожну функцію активації.|[Лекція 2](dl_lec2.qmd), [Лекція 3](dl_lec3.qmd), <https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial3/Activation_Functions.html>|
|Теорема про тотожну функцію активації.|[Лекція 2](dl_lec2.qmd)|
|Функції втрат. Їх диференціювання. Приклади. |[Лекція 2](dl_lec2.qmd), [Лекція 3](dl_lec3.qmd)|
|Метод зворотного поширення (backpropagation)|[Лекція 2](dl_lec2.qmd), [Лекція 3](dl_lec3.qmd), <https://d2l.ai/chapter_multilayer-perceptrons/backprop.html>|
|Пряме та зворотне поширення (forward and back propagation) на прикладі глибокої нейронної мережі з $L$ шарами|[Лекція 3](dl_lec3.qmd), [Лаб 3](dl_lab3.qmd)|
|Компроміс зсуву та дисперсії (bias-variance tradeoff). |[Лекція 4](dl_lec4.qmd)|
|Регуляризація нейронних мереж: L1/L2. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd)|
|Регуляризація нейронних мереж: Dropout. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd)|
|Нормалізація  нейронних мереж. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd)|
|Ініціалізація нейронних мереж.|[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd), <https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial4/Optimization_and_Initialization.html>|
|Оптимізація нейронних мереж: Mini-batch GD, Stochastic GD. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd), <https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial4/Optimization_and_Initialization.html>|
|Оптимізація нейронних мереж: SGD with Momentum. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd), <https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial4/Optimization_and_Initialization.html>|
|Оптимізація нейронних мереж: Adam. |[Лекція 4](dl_lec4.qmd), [Лаб 4](dl_lab4.qmd), <https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial4/Optimization_and_Initialization.html>|
|Згорткові нейронні мережі. Основні властивості. Означення згортки. |[Лекція 7](dl_lec7.qmd), [Лаб 7](dl_lab7.qmd), <https://d2l.ai/chapter_convolutional-neural-networks/index.html>|
|Згорткові нейронні мережі. Stride, pooling, dilation, padding. |[Лекція 7](dl_lec7.qmd), [Лаб 7](dl_lab7.qmd), <https://d2l.ai/chapter_convolutional-neural-networks/index.html>|
